name: py_elec_env
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - cython=0.29.16
  - fontconfig=2.13.1
  - freetype=2.10.1
  - icu=64.2
  - intel-openmp
  - jpeg
  - kiwisolver=1.2.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libxml2=2.9.10
  - llvmlite=0.31.0
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - numba=0.48.0
  - numpy=1.18.1
  - occt=7.4.0
  - openssl=1.1.1f
  - pip=20.0.2
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - python=3.7.3
  - python-dateutil
  - python_abi=3.7
  - pythonocc-core=7.4.0
  - qt=5.12.5
  - scipy=1.4.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - tbb=2020.1
  - tornado=6.0.4
  - wheel=0.34.2
  - zlib=1.2.11
  - pip:
    - numpy-quaternion==2019.12.11.22.25.52
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
